import fs from "node:fs";
import path from "node:path";
import { loadSessions, getSessionsFilePath, Session } from "./sessions.js";

const CONTEXT_FILENAME = "CEREUS.md";

export function writeContextFile(worktreePath: string, session: {
  id: string;
  repo: string;
  branch: string;
  prompt?: string;
}): void {
  const sessionsPath = getSessionsFilePath();
  const sessions = loadSessions();

  const otherSessions = sessions
    .filter((s) => s.id !== session.id && s.status === "running")
    .map(formatSessionSummary)
    .join("\n");

  const content = `# Cereus Session Context

> This file is auto-generated by [cereus](https://github.com/adheus/cereus).
> It provides context about this session and other active sessions.

## This Session

- **ID**: ${session.id}
- **Repository**: ${session.repo}
- **Branch**: ${session.branch}
${session.prompt ? `- **Task**: ${session.prompt}` : ""}

## Active Sessions

${otherSessions || "_No other active sessions._"}

## Sessions File

Full session data is available at: \`${sessionsPath}\`

## Cereus Commands

You can manage sessions using the \`cereus\` CLI:

- \`cereus new <repo> <identifier>\` — create a new session
- \`cereus list\` — list all active sessions
- \`cereus attach <identifier>\` — attach to a session
- \`cereus kill <identifier>\` — kill a session
- \`cereus alias add|list|remove\` — manage repo aliases
- \`cereus config\` — view/edit configuration

### Options for \`new\` and \`attach\`:
- \`--smart\` — auto-split panes, then new windows (default)
- \`--split\` — split current tmux pane
- \`--window\` — new tmux window
- \`--hidden\` — run in background
`;

  fs.writeFileSync(path.join(worktreePath, CONTEXT_FILENAME), content);
}

function formatSessionSummary(s: Session): string {
  return `- **${s.id}** (${s.repo}/${s.branch}) — ${s.status}${s.prompt ? ` — _${s.prompt}_` : ""}`;
}

export function removeContextFile(worktreePath: string): void {
  const filePath = path.join(worktreePath, CONTEXT_FILENAME);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}
